import { describe, expect, it } from 'vitest'
import { signRequest } from '../src/core.js'

// Vectors generated by the reference EXO2-HMAC-SHA256 implementation in
// test/signing-vectors/ (fixed clock and credentials).
// Regenerate with: cd test/signing-vectors && go run .

const API_KEY = 'test-key'
const SECRET = '0123456789abcdef'
const EXPIRES = 1750000000

const VECTORS: Array<{ name: string; header: string; args: Parameters<typeof signRequest>[0] }> = [
  {
    name: 'get-no-body-no-query',
    header:
      'EXO2-HMAC-SHA256 credential=test-key,expires=1750000000,signature=xdOhvE746GnETaaYoflEK4ucguvSsVJW1fnXZAboV54=',
    args: {
      method: 'GET',
      path: '/instance/0b12cb6b-7e3e-4c0e-9e10-1e5d8a7c4b2a',
      body: '',
      query: {},
      apiKey: API_KEY,
      apiSecret: SECRET,
      expires: EXPIRES,
    },
  },
  {
    name: 'get-query',
    header:
      'EXO2-HMAC-SHA256 credential=test-key,signed-query-args=labels;manager-type,expires=1750000000,signature=gVbvdwVNMPtM6KFi0aNOcMfJ6P4kJhgUX/r6KT+mt9k=',
    args: {
      method: 'GET',
      path: '/instance',
      body: '',
      query: { labels: 'web', 'manager-type': 'instance-pool' },
      apiKey: API_KEY,
      apiSecret: SECRET,
      expires: EXPIRES,
    },
  },
  {
    name: 'get-query-encoding',
    header:
      'EXO2-HMAC-SHA256 credential=test-key,signed-query-args=labels,expires=1750000000,signature=c52iAK8YkX82SvWfz2L0NB3ifLH+B4tVwMAhdczd+hA=',
    args: {
      method: 'GET',
      path: '/instance',
      body: '',
      query: { labels: 'a b' },
      apiKey: API_KEY,
      apiSecret: SECRET,
      expires: EXPIRES,
    },
  },
  {
    name: 'post-body',
    header:
      'EXO2-HMAC-SHA256 credential=test-key,expires=1750000000,signature=ZqEE7tXE57UIydqAXHsqZgGA/UzTft1t9PFFVKvNGtA=',
    args: {
      method: 'POST',
      path: '/instance',
      body: '{"disk-size":10,"name":"foo"}',
      query: {},
      apiKey: API_KEY,
      apiSecret: SECRET,
      expires: EXPIRES,
    },
  },
  {
    name: 'put-body-query',
    header:
      'EXO2-HMAC-SHA256 credential=test-key,signed-query-args=include-deprecated,expires=1750000000,signature=X8y11+VpWDTXeX7V88MtwWBn33rCh4d+d6nLtDkzC3g=',
    args: {
      method: 'PUT',
      path: '/instance/0b12cb6b-7e3e-4c0e-9e10-1e5d8a7c4b2a',
      body: '{"tags":["a"]}',
      query: { 'include-deprecated': 'true' },
      apiKey: API_KEY,
      apiSecret: SECRET,
      expires: EXPIRES,
    },
  },
  {
    name: 'delete-no-body',
    header:
      'EXO2-HMAC-SHA256 credential=test-key,expires=1750000000,signature=7ZZ1cRu5alwvGdq5CVMcme5fbWCinBUfxeQmyb3IDoA=',
    args: {
      method: 'DELETE',
      path: '/vpc/0b12cb6b-7e3e-4c0e-9e10-1e5d8a7c4b2a',
      body: '',
      query: {},
      apiKey: API_KEY,
      apiSecret: SECRET,
      expires: EXPIRES,
    },
  },
]

// Runs the EXO2-HMAC-SHA256 reference-vector suite in the current test
// environment. Import from a *.test.ts file to register it.
export function registerSigningTests() {
  describe('signRequest (EXO2-HMAC-SHA256)', () => {
    for (const v of VECTORS) {
      it(`matches Go vector: ${v.name}`, () => {
        expect(signRequest(v.args)).toBe(v.header)
      })
    }

    it('sorts query parameter names in the signature', () => {
      const header = signRequest({
        method: 'GET',
        path: '/instance',
        body: '',
        query: { zebra: '1', alpha: '2', mid: '3' },
        apiKey: API_KEY,
        apiSecret: SECRET,
        expires: EXPIRES,
      })
      expect(header).toContain('signed-query-args=alpha;mid;zebra')
    })

    it('omits signed-query-args when there is no query', () => {
      const header = signRequest({
        method: 'GET',
        path: '/zone',
        body: '',
        query: {},
        apiKey: API_KEY,
        apiSecret: SECRET,
        expires: EXPIRES,
      })
      expect(header).not.toContain('signed-query-args')
    })
  })
}
