// Generates src/generated/operations.ts: one flat method per OpenAPI
// operationId on GeneratedExoscaleClient, with all parameters (path, query,
// body) merged into a single params object argument.
//
// Request type rules (collision-free):
//   - inline body          -> generated <Op>Request interface (params merged in)
//   - $ref body, no params -> the referenced schema type is used directly
//   - $ref body + params   -> referenced type & { path/query fields }
//   - no body, has params  -> generated <Op>Request interface (params only)
//
// Response rules:
//   - $ref 200 -> the referenced type
//   - inline object/array 200 -> generated <Op>Response type
//   - 204 / no content -> void

import type { JSON, Operation, Parameter, Spec } from './model.js'
import { resolveRef } from './model.js'
import {
  baseType,
  buildPropDesc,
  refName,
  renderNamedType,
  renderToWireFn,
  simplePropertyExpr,
  sortedProps,
  type RenderCtx,
  type TypeRegistry,
} from './types.js'
import { docLines, renderDoc, renderDocBlock, toCamel, toLowerCamel } from './naming.js'

interface ParamInfo {
  wireName: string
  tsName: string
  doc: string
  typeExpr: string
  queryExpr: string | null // stringification RHS for query params
  required: boolean
}

interface ReqField {
  wireName: string
  tsName: string
  required: boolean
  nullable: boolean
  doc: string
  typeExpr: string
  bodyToExpr?: string // body fields only: wire expression for v.tsName
  isBody: boolean
}

interface OpCode {
  typeCode: string
  method: string
}

interface RespInfo {
  retType: string
  decode: string | null
  typeCode: string
}

export function generateOperations(spec: Spec, registry: TypeRegistry): string {
  const header = [
    '// Code generated by @exoscale/sdk generator. DO NOT EDIT.',
    `// Source: ${spec.info.title} ${spec.info.version} (openapi ${spec.openapi})`,
    '',
  ].join('\n')

  const usedTypes = new Set<string>()
  const usedWireFns = new Set<string>()
  let usesIso = false

  const ops = spec.operations.map((op) =>
    renderOperation(op, spec, registry, usedTypes, usedWireFns, () => (usesIso = true)),
  )

  const imports: string[] = []
  const wireFns = [...usedWireFns].sort()
  if (wireFns.length > 0) {
    imports.push(`import { ${wireFns.join(', ')} } from './schemas.js'`)
  }
  const types = [...usedTypes].sort()
  if (types.length > 0) {
    imports.push(`import type { ${types.join(', ')} } from './schemas.js'`)
  }
  imports.push(`import { ${usesIso ? 'isoDateTime, ' : ''}type ClientCore } from '../core.js'`)

  const typeDecls = ops
    .map((o) => o.typeCode)
    .filter((c) => c !== '')
    .join('\n')

  return (
    header +
    imports.join('\n') +
    '\n\n' +
    (typeDecls !== '' ? typeDecls + '\n' : '') +
    'export abstract class GeneratedExoscaleClient {\n  protected abstract core: ClientCore\n\n' +
    ops.map((o) => o.method).join('\n\n') +
    '\n}\n'
  )
}

function paramInfo(
  op: Operation,
  p: Parameter,
  usedTypes: Set<string>,
  setUsesIso: () => void,
): ParamInfo {
  let typeExpr: string
  if (p.schema.$ref !== undefined) {
    typeExpr = refName(p.schema.$ref)
    usedTypes.add(typeExpr)
  } else {
    typeExpr = simplePropertyExpr(p.schema)
  }

  let queryExpr: string | null = null
  if (p.in === 'query') {
    const name = toLowerCamel(p.name)
    if (p.schema.$ref !== undefined) {
      queryExpr = `String(params.${name})`
    } else if (p.schema.format === 'date-time') {
      queryExpr = `isoDateTime(params.${name})`
      setUsesIso()
    } else if (
      p.schema.type === 'integer' ||
      p.schema.type === 'number' ||
      p.schema.type === 'boolean'
    ) {
      queryExpr = `String(params.${name})`
    } else {
      queryExpr = `params.${name}`
    }
  }

  return {
    wireName: p.name,
    tsName: toLowerCamel(p.name),
    doc: renderDoc(p.description),
    typeExpr,
    queryExpr,
    required: p.required,
  }
}

function renderRequestInterface(name: string, fields: ReqField[]): string {
  const body = fields
    .map((f) => {
      const opt = f.required ? '' : '?'
      const nul = f.nullable ? ' | null' : ''
      return `${f.doc ? `${f.doc}\n` : ''}  ${f.tsName}${opt}: ${f.typeExpr}${nul}`
    })
    .join('\n')
  return `export interface ${name} {\n${body}\n}\n`
}

function responseInfo(
  op: Operation,
  typeName: string,
  registry: TypeRegistry,
  usedTypes: Set<string>,
  usedWireFns: Set<string>,
): RespInfo {
  if (!op.has200Content) {
    return { retType: 'void', decode: null, typeCode: '' }
  }

  const r = op.response200!
  if (r.$ref !== undefined) {
    const n = refName(r.$ref)
    usedTypes.add(n)
    let decode: string | null = null
    if (registry.hasWire(n)) {
      decode = `fromWire${n}`
      usedWireFns.add(decode)
    }
    return { retType: n, decode, typeCode: '' }
  }

  const t = baseType(r)
  if (t === 'array') {
    const items = r.items
    if (items === undefined) throw new Error(`${op.operationId}: array response without items`)
    if (items.$ref !== undefined) {
      const n = refName(items.$ref)
      usedTypes.add(n)
      let decode: string | null = null
      if (registry.hasWire(n)) {
        decode = `(w) => (w as any[]).map(fromWire${n})`
        usedWireFns.add(`fromWire${n}`)
      }
      return { retType: `${n}[]`, decode, typeCode: '' }
    }
    return inlineResponseType(op, typeName, registry, r, usedTypes, usedWireFns)
  }

  if (t === 'object' || t === 'record') {
    return inlineResponseType(op, typeName, registry, r, usedTypes, usedWireFns)
  }

  // Scalar 200 body: returned as-is.
  return { retType: simplePropertyExpr(r), decode: null, typeCode: '' }
}

function inlineResponseType(
  op: Operation,
  typeName: string,
  registry: TypeRegistry,
  schema: JSON,
  usedTypes: Set<string>,
  usedWireFns: Set<string>,
): RespInfo {
  const name = `${typeName}Response`
  const respCtx: RenderCtx = {
    registry,
    out: [],
    dir: 'from',
    trackTypes: usedTypes,
    trackWireFns: usedWireFns,
  }
  const code = renderNamedType(name, schema, respCtx, schema.description ?? schema.title)
  // fromWire<name> is defined in this same file (no import needed); it exists
  // only when the response type needs wire transforms.
  const decode = registry.hasWire(name) ? `fromWire${name}` : null
  return { retType: name, decode, typeCode: respCtx.out.join('\n') + code }
}

// operationDoc renders the JSDoc block for a method: its description, an
// Errors section built from the non-2xx responses, and @see links to the
// external docs of the operation's tags.
function operationDoc(op: Operation, spec: Spec): string {
  const groups: string[][] = [docLines(op.description || op.summary)]

  if (op.errors.length > 0) {
    const errors: string[] = ['Errors:']
    for (const e of op.errors) {
      errors.push('', `**${e.code}**`, ...docLines(e.description))
    }
    groups.push(errors)
  }

  const tags: string[] = []
  for (const name of [...new Set(op.tags)].sort()) {
    const docs = spec.tags.find((t) => t.name === name)?.externalDocs
    const url = docs?.url
    if (docs === undefined || typeof url !== 'string' || url === '') continue
    tags.push(`@see ${url} ${docs.description ?? name}`)
  }

  return renderDocBlock([...groups, tags])
}

function renderOperation(
  op: Operation,
  spec: Spec,
  registry: TypeRegistry,
  usedTypes: Set<string>,
  usedWireFns: Set<string>,
  setUsesIso: () => void,
): OpCode {
  const typeName = toCamel(op.operationId)
  const funcName = toLowerCamel(op.operationId)
  const doc = operationDoc(op, spec)

  const pathParams = op.parameters.filter((p) => p.in === 'path')
  const queryParams = op.parameters.filter((p) => p.in === 'query')
  const hasParams = pathParams.length > 0 || queryParams.length > 0

  const params = new Map<string, ParamInfo>()
  for (const p of op.parameters) {
    params.set(p.name, paramInfo(op, p, usedTypes, setUsesIso))
  }

  const bodySchema = op.requestBody
  const bodyIsRef = bodySchema !== undefined && bodySchema.$ref !== undefined
  const bodyIsInline = bodySchema !== undefined && bodySchema.$ref === undefined

  // ---- request type ----------------------------------------------------------
  let typeCode = ''
  let paramDecl = ''
  let bodyToWire: string | null = null
  let anyRequired = false

  if (bodyIsInline) {
    const name = `${typeName}Request`
    registry.declareObject(name)
    const reqCtx: RenderCtx = {
      registry,
      out: [],
      dir: 'to',
      trackTypes: usedTypes,
      trackWireFns: usedWireFns,
    }
    const fields: ReqField[] = []

    for (const p of [...pathParams, ...queryParams]) {
      const info = params.get(p.name)!
      fields.push({
        wireName: p.name,
        tsName: info.tsName,
        required: p.in === 'path',
        nullable: false,
        doc: info.doc,
        typeExpr: info.typeExpr,
        isBody: false,
      })
      if (p.in === 'path') anyRequired = true
    }

    const required = new Set<string>(bodySchema.required ?? [])
    for (const [wireName, prop] of sortedProps(bodySchema)) {
      const d = buildPropDesc(reqCtx, name, prop, wireName, required.has(wireName))
      if (d.required) anyRequired = true
      fields.push({
        wireName,
        tsName: d.tsName,
        required: d.required,
        nullable: d.nullable,
        doc: d.doc,
        typeExpr: d.typeExpr,
        bodyToExpr: d.toExpr,
        isBody: true,
      })
    }

    typeCode += reqCtx.out.join('\n')
    typeCode += renderRequestInterface(name, fields)

    const bodyFields = fields.filter((f) => f.isBody)
    if (bodyFields.length > 0) {
      typeCode += renderToWireFn(
        name,
        bodyFields.map((f) => ({
          tsName: f.tsName,
          wireName: f.wireName,
          nullable: f.nullable,
          toExpr: f.bodyToExpr!,
        })),
      )
      bodyToWire = `toWire${name}(params)`
      // toWire<name> is defined in this same file (no import needed).
    }
    paramDecl = name
  } else if (bodyIsRef) {
    const ref = refName(bodySchema.$ref)
    usedTypes.add(ref)
    const target = resolveRef(bodySchema.$ref, spec.schemas)
    const t = baseType(target)
    if (t !== 'object' && t !== 'record') {
      throw new Error(`${op.operationId}: $ref body must point to an object schema`)
    }
    bodyToWire = `toWire${ref}(params)`
    usedWireFns.add(`toWire${ref}`)
    if (hasParams) {
      const extra = op.parameters
        .map((p) => {
          const info = params.get(p.name)!
          return `${info.doc ? `${info.doc}\n      ` : ''}${info.tsName}${p.in === 'path' ? '' : '?'}: ${info.typeExpr}`
        })
        .join(';\n      ')
      paramDecl = `${ref} & {\n      ${extra}\n    }`
      if (pathParams.length > 0) anyRequired = true
    } else {
      paramDecl = ref
    }
  } else if (hasParams) {
    const name = `${typeName}Request`
    registry.declareObject(name)
    const fields: ReqField[] = op.parameters.map((p) => {
      const info = params.get(p.name)!
      return {
        wireName: p.name,
        tsName: info.tsName,
        required: p.in === 'path',
        nullable: false,
        doc: info.doc,
        typeExpr: info.typeExpr,
        isBody: false,
      }
    })
    typeCode += renderRequestInterface(name, fields)
    paramDecl = name
    if (pathParams.length > 0) anyRequired = true
  }

  // A request body is always part of the params object, so the params object
  // itself must be required whenever there is a body.
  if (bodyToWire !== null) anyRequired = true

  // ---- response ----------------------------------------------------------------
  const resp = responseInfo(op, typeName, registry, usedTypes, usedWireFns)
  typeCode += resp.typeCode

  // ---- method body ---------------------------------------------------------------
  const lines: string[] = []

  let pathVar: string
  if (pathParams.length > 0) {
    let tpl = op.path
    for (const p of pathParams) {
      const segment = '${encodeURIComponent(params.' + toLowerCamel(p.name) + ')}'
      tpl = tpl.split(`{${p.name}}`).join(segment)
    }
    lines.push(`    const path = \`${tpl}\``)
    pathVar = 'path'
  } else {
    pathVar = JSON.stringify(op.path)
  }

  const prefix = anyRequired ? 'params.' : 'params?.'
  if (queryParams.length > 0) {
    lines.push('    const query: Record<string, string> = {}')
    for (const q of queryParams) {
      const info = params.get(q.name)!
      lines.push(
        `    if (${prefix}${info.tsName} !== undefined) query['${q.name}'] = ${info.queryExpr!.replace('params.', prefix)}`,
      )
    }
  }

  if (bodyToWire !== null) {
    lines.push(`    const body = ${bodyToWire}`)
  }

  const opts: string[] = []
  if (bodyToWire !== null) opts.push('body')
  if (queryParams.length > 0) opts.push('query')
  if (resp.decode !== null) opts.push(`decode: ${resp.decode}`)
  if (op.operationId === 'list-zones') opts.push('skipAuth: true')
  const optsStr = opts.length > 0 ? `, { ${opts.join(', ')} }` : ''
  lines.push(`    return this.core.request('${op.method.toUpperCase()}', ${pathVar}${optsStr})`)

  const paramSig = paramDecl === '' ? '' : `params${anyRequired ? '' : '?'}: ${paramDecl}`
  const method = `${doc ? `${doc}\n` : ''}  ${funcName}(${paramSig}): Promise<${resp.retType}> {\n${lines.join(
    '\n',
  )}\n  }`

  return { typeCode, method }
}
