// Generates src/generated/schemas.ts: one TS type per OpenAPI component
// schema, plus the toWire*/fromWire* wire transform functions.

import type { Spec } from './model.js'
import { toCamel } from './naming.js'
import { renderNamedType, type RenderCtx, type TypeRegistry } from './types.js'

export function generateSchemas(spec: Spec, registry: TypeRegistry): string {
  const header = [
    '// Code generated by @exoscale/sdk generator. DO NOT EDIT.',
    `// Source: ${spec.info.title} ${spec.info.version} (openapi ${spec.openapi})`,
    '',
  ].join('\n')

  const ctx: RenderCtx = { registry, out: [], dir: 'both' }
  for (const kebab of [...spec.schemas.keys()].sort()) {
    const name = toCamel(kebab)
    const schema = spec.schemas.get(kebab)!
    ctx.out.push(renderNamedType(name, schema, ctx, schema.description ?? schema.title))
  }

  return header + ctx.out.join('\n')
}
